### ISSUE TITLE
When the container restarts it generates a new SSH key?

### ISSUE THREAD

**Issue by secoldPrivate** [ericbarch/dockuwiki#6]
That's a problem because the only way to fix it is to ssh into the remote server, and look at the docker logs, add the key to github again.

What would be neat is if you could specify a volume where the key was stored, so we could use the host machine's SSH key. 

Oh and a compose file for all 3 containers with SSH setup would be amazing.

**Comment by ericbarch** [comment]
Presently, the bootstrap_wiki.sh script does check to see if a key has already been re-generated and will continue to re-use this key, even through reboots. If you re-create the container, then yes, you will end up with a new SSH key. This is currently the expected behavior.

Source: https://github.com/ericbarch/dockuwiki/blob/02586ea2e224133740ecee6353e7c29c15eadb01/wiki_home/bootstrap_wiki.sh#L19

Please feel free to create issues for feature enhancements.
